### ISSUE TITLE
Show the Options page to the user when they install the extension.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-browser-extension#13]
All features are turned off by default, so we should direct them to the options page after they install the extension so they can choose which features they want.

**Comment by Lesko987** [comment]
I would recomend a different system. Options should be 3 state. On / Off / Default. 

Default would be defined by a developer when a modul is fully tested and all bugs corrected.

I think that functions that are connected to hints, hower or othervise alter the behavior and look of the page should always be defaulted to Off and user could turn them on if he wants. Inserting new clickable options in menus or "buttons" on the page could be defaulted to On when functional.

That way after instaling the extension users would already have some functionality abailable.

Aleš

**Comment by jmegenealogy** [comment]
I think adding a "default" state would be a separate to-do item. The user wouldn't need to see the option -- just the on/off switch.

I still think it would be valuable to direct the user to the options page so they can customize it to their likely before they start using it.

Anyone else have any opinions?

**Comment by shogenapps** [comment]
I agree with both of you.  Buttons could be added to menus by default, and on installation, new users should be given the options page.  I think it will be a good idea to categorise and sort the features first.

**Comment by ke4tch** [comment]
So users who install the extension for the first time should be directed to configure the options.

What is the mechanism for notifying users when a new feature has been incorporated and there are more options to be configured?

**Comment by harrislineage** [comment]
First, I would suggest moving to an [embedded options](https://developer.chrome.com/docs/extensions/mv3/options/#embedded_options) page that can be called directly from the Extension (App Features) Menu with `chrome.runtime.openOptionsPage()`. Since the Menu is shown by default (and empty on new installs currently) the "Extension Options" option will be the only item/link available and will hopefully make sense to the non-technical users who may not know how to pin the extension to keep it visible, know to click on it to get to option page without guided directions, etc.

If we later add defaults to the menu, then we can make sure the "Extension Options" option is prominent (maybe bold or highlighted, or some other method).

Second, it is simple to use the [onInstalled event]() that will trigger on first install / update. I would suggest that this navigate to an general onboarding page (Help:WikiTree Browser Extension perhaps). As an alternative, we have an internal onboarding page that we will launch from core/onboarding.html or similar.
```
chrome.runtime.onInstalled.addListener((reason) => {
  if (reason === chrome.runtime.OnInstalledReason.INSTALL) {
    chrome.tabs.create({
      url: '...'
    });
  }
});
```

@ke4tch updates would be similar, but we can use the UPDATE instead of INSTALL flag and pull from something like core/changelog.html.

**Comment by shogenapps** [comment]
This can be changed in the future if you want to direct users to a webpage or something on install, but I've submitted a pull request to do what Jamie suggested originally - open the options page on installation.
