### ISSUE TITLE
Organize List of "Degrees from" people at bottom of profile

### ISSUE THREAD

**Issue by Clarke-11007** [wikitree/wikitree-browser-extension#147]
The list of people at the bottom of your (any) profile has an organization, mostly alphabetic (except for the primary profile which is always first) - BUT - wouldn't it be nice if .... you could SORT the list by # of degrees away you are instead?  ALSO, wouldn't it be nice if there were the option to format the list as a bulleted list, one person per line, so it was easier to find someone - and not get distracted by line breaks in between first and last names (or names and degrees) ?

AND ... while we're at it (bonus WIBNI) - wouldn't it be nice if there were an additional icon for those who were not only connected by a number of degrees, but actually RELATED to you as a (likely distant) cousin!

Anyone ready to tackle that?

**Comment by shogenapps** [comment]
This can be done as an addition to (or adaptation of) the Distance and Relationship feature, because it would be done in the same way (get the Connection Finder and Relationship Finder results and store them) but multiplied by 10 (or however many profiles are involved).   Having it work only on click would save a lot of processing, I imagine.

**Comment by shogenapps** [comment]
I am doing this.

**Comment by shogenapps** [comment]
I've put in a PR (#157).
