### ISSUE TITLE
Register who created each feature and who contributed to each feature, so we can give credit to those who contribute.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-browser-extension#225]
The best way to do this might be to include this data in register_feature_options.js -- one for "creators", and one for "contributors".

Then we could include this data on the options page somewhere when showing the information on each feature.

**Comment by RobPavey** [comment]
We might need to do a bit of cleanup or refactoring in this area. I intended register_feature_options as a place to register the options - i.e. the things that the user can edit.

But maybe there needs to be a larger concept of a "feature" independent of just options.

**Comment by Lesko987** [comment]
Rob, I think it should be as simple as adding 
  creators: [{name:"Aleš Trtnik", wikitreeid:"Trtnik-2"}],
  contributors: [],
to each option.

I would also like to add the page types where the option can be active, since I think a lot of code runs on pages where there is absolutely no need for it. See https://github.com/wikitree/wikitree-browser-extension/issues/217 for more.

**Comment by Lesko987** [comment]
This is now implemented. See https://github.com/wikitree/wikitree-browser-extension/tree/OptionsUpdate
