### ISSUE TITLE
Decide how to handle supporting multiple browsers.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-browser-extension#3]

**Comment by RobPavey** [comment]
I can provide advice on this since I have developed two extensions (Sourcer and AGC) that work in Chrome (and other Chromium-based browsers), Firefox and Safari (including on iOS).

One of the biggest issues is MV3 vs MV2. Currently if you start a new extension now on Chrome it has to use MV3. But Firefox and Safari do not yet appear to support MV3 so you have to use MV2. Firefox say they will have MV3 support by the end of the year.

So you have to use MV3 for the Chrome version and MV2 for the Firefox and Safari versions. As it turns out this is not difficult. I have a single code base for all versions. I do have a separate manifest.json for each browser type.

The code for Sourcer is public here: https://github.com/RobPavey/wikitree-sourcer

**Comment by RobPavey** [comment]
You do need to use XCode to build the Safari version. This requires a Mac. There is a tool that will create the xcode project for an extension automatically. This is what I used. It is documented here: https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

**Comment by RobPavey** [comment]
Assuming that we need to use MV2 for Firefox in our initial releases we will need a separate manifest.json file.

Can we setup the webpack build so that we can say "build for Chrome", "build for Firefox" etc and it copes the appropriate manifest file into dist? I assume so.

**Comment by jmegenealogy** [comment]
@PeWu , I'm still learning about webpack but how easy would it be to set it up to build a separate Chrome and Firefox version?

**Comment by jmegenealogy** [comment]
I took a shot at creating the manifest for Firefox and it loaded into Firefox with no errors (https://github.com/wikitree/wikitree-browser-extension/blob/development/src/manifest/manifest-firefox.json), but the options won't save so I might have done something wrong. https://github.com/wikitree/wikitree-browser-extension/issues/66

**Comment by jmegenealogy** [comment]
Firefox is working now, so the last one to do is Safari.

**Comment by RobPavey** [comment]
I have Safari working for a couple of extensions but not with webpack. 

In Sourcer I have a browser_variants folder with a Safari subfolder that contains the manifest.json file and the XCode project: https://github.com/ColinT152/wikitree-sourcer/tree/main/browser_variants/safari

The XCode project points to the regular source code under "extension" except for the manifest - where it points to the Safari one.

For Safari Web Extensions there is an App involved as well as an extension - the App is how it is packaged for the App store.

To test (on local, Mac, physical iOs device or iOS simulator you build and run in xcode. To make a release you build an Archive in XCode.

The simple/hacky way to make it work with webpack would be to have the xcode project point to the files in the dist folder. This seems a bit odd though - since when the dist folder is cleaned there is nothing there. So there may be a different way where xCode uses webpack when you do a build/archive. Or a third option would be to have webpack/npm run xcode from the command line.

Some research probably should be done. A quick google found this which may or may not help: https://github.com/csandman/xcode-build-webpack-plugin
That seems like the third option I mentioned above.

**Comment by shogenapps** [comment]
Done.
