### ISSUE TITLE
Decision on edit addons

### ISSUE THREAD

**Issue by Lesko987** [wikitree/wikitree-browser-extension#5]
It is obvious that editing addon need to be added to the editing toolbar. I have a menu with submenus with multiple options to execute,, AGC optionally shows the buttons, I am sure others will want to add something near the toolbar.

We need to set some standard or we will soon run out of space.

**1)  Where to put the menu?**
My idea is to add a few buttons to the right of the toolbar and each would have a dropdown menu with multiple options. 
Top level buttons could be 

**2) Top items in menu:**
BIO | SOURCES | TEMPLATES | CLEANUP | MISC

Bio would have biography writers, timeline creators, ...

Sources would have most of the items from Sourcerer and Paste sources from WT+ extension. 

Template would have all template options from WT+

Cleanup would hold AGC item, my Automated corrections (What EditBOT corrects)

And Misc would have all that doesn't fit into the first 4 groups.

**3) Different menus on each page type.**
On other types of pages (Space, Category, Template, Other) the added buttons would be different like I have different options for each page type. For instance Category pages would get EditBOT operations, and other differences are usefull.

**4) Menu Definition:**
I have the menus defined in my extension, but the implementation and definition should be moved to the core folder where we would also define the content similar to the main menu.

Any thoughts or ideas about this.

Aleš

**Comment by RobPavey** [comment]
First question is where the extension should add a menu. My expectation would be that the menu would be an extension popup (like Sourcer) and not part of the web page. What is the advantage to putting a menu in each web page?

Second, I see no advantage in putting the Sourcer menu inside another menu. It just adds extra clicks. I have said from the start that I don't see any good reason to combine the Sourcer extension with this new extension. Is no one listening?

**Comment by Lesko987** [comment]
Rob, 
It is your decision if you will keep the Sourcerer extensen separate. I decided that I will transfer WT+ to the Wikitree one.

And I am talking about the menus for editing on edit pages just abowe the editbox next to the other buttons.

**Comment by RobPavey** [comment]
Ah, I was thinking that you were also talking about the menu at the top of the page on all wikitree pages.

OK, so we are talking about the edit toolbar. I wonder about the pros and cons of adding things into the row of edit buttons vs using an extension popup. If I was starting over with AGC I would probably use an extension popup rather than modifying the page.

Pros of adding buttons to page:
- Maybe simpler code since it can all be in the content script (no popup script and messaging required)
- there are probably some more that are not coming to my mind

Pros of using popup:
- The page is not modified (less change of undesired interactions with other extensions)
- It is the "standard" way of adding a menu in an extension?
- The majority of the code can be loaded when the popup is invoked (so it is not loaded every time to go to the page). This also allows easy use of javascript modules.

One other difference is that the row of the edit buttons is "close" to the edit box. If these are things that the user uses while editing in that box this could be seen as an advantage. However, the edit box is tall and this means that the edit buttons are often scrolled out of the window when editing - while the popup is always accessible without scrolling.

**Comment by Lesko987** [comment]
I didn't even consider popup menu in the past, since it is not often used on web pages. I know only goole web apps are using it. Normal web pages usually don't. 
But it is a good solution and usually very handy to use. We might do both.

The problem I see with popups are mobile devices (phones and tablets). I think it is not that simple to use right click there. I checked the numbers and 45% of requests are from desktop computers and 55% from phones and tablets. On Edit pages the percentage is a bit different and desktop has 55% usage and mobile is down to 45%. But that is still a lot of mobile usage.

**Comment by shogenapps** [comment]
Rob, I'm thinking about the Auto Bio that I have in the BEE... I just think that the toolbar is the best (most user-friendly) place for it.  People see it there where they're typing.  The cursor is usually around the same place.  Having to move the cursor up to the extension icon, click it, and then find the button that will produce the Auto Bio seems like a lot of trouble.  It's also out of sight - out of mind.  Having the button right there seems like the best way, to me.  
Having said that, I do understand your point about the code only being loaded when necessary when it's in the pop-up.  

Aleš, I'm not sure you're talking about the same thing.  Rob's talking about the pop-up page that appears (or can appear) when you click the extension icon rather than anything to do with right-clicking.  (The new extension doesn't have one of these yet.)

**Comment by RobPavey** [comment]
Sorry, I am not talking about the contect menu (the popup that you get when you right click) though that can also be useful.

What I am talking about is the extension popup. This is a key part of browser extensions. Each extension can have an icon that shows up in the url bar of the browser. Clicking this icon invokes the extensions popup (usually called popup.html) which can be any html but is often in the form of a menu. This is how WikiTree Sourcer works.

**Comment by Lesko987** [comment]
Indeed I was thinking about right click on the web pabe (context menu). I just saw it yesterday in Rob's video, so I thought he was talking about that. 
Popup on an extension icon is tricky. It can be hidden and users don't even know they can click on it. And it is further away from the edit box.
